package com.zurrtum.create.content.kinetics.deployer;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.mojang.serialization.DynamicOps;
import com.zurrtum.create.AllRecipeSerializers;
import com.zurrtum.create.AllRecipeTypes;
import com.zurrtum.create.content.processing.recipe.ProcessingOutput;
import com.zurrtum.create.foundation.recipe.ComponentsIngredient;
import com.zurrtum.create.foundation.recipe.IngredientText;
import net.minecraft.recipe.Ingredient;
import net.minecraft.recipe.RecipeSerializer;
import net.minecraft.recipe.RecipeType;
import net.minecraft.text.Text;
import net.minecraft.world.World;
import org.jetbrains.annotations.Nullable;

import java.util.List;

public record DeployerApplicationRecipe(
    List<ProcessingOutput> results, boolean keepHeldItem, Ingredient target, Ingredient ingredient,
    @Nullable ComponentsIngredient stageRequirement
) implements ItemApplicationRecipe {
    public DeployerApplicationRecipe(List<ProcessingOutput> results, boolean keepHeldItem, Ingredient target, Ingredient ingredient) {
        this(results, keepHeldItem, target, ingredient, null);
    }

    // Sequenced-assembly steps generated by SequencedAssemblyRecipe attach a stageRequirement so a deploying
    // step only matches a transitional item that's at exactly this assembly step - see ComponentsIngredient.
    @Override
    public boolean matches(ItemApplicationInput input, World world) {
        return (stageRequirement == null || stageRequirement.test(input.target())) && ItemApplicationRecipe.super.matches(input, world);
    }

    @Override
    public RecipeSerializer<DeployerApplicationRecipe> getSerializer() {
        return AllRecipeSerializers.DEPLOYING;
    }

    @Override
    public RecipeType<DeployerApplicationRecipe> getType() {
        return AllRecipeTypes.DEPLOYING;
    }

    public static Text getDescriptionForAssembly(DynamicOps<JsonElement> ops, JsonObject object) {
        return Ingredient.DISALLOW_EMPTY_CODEC.parse(ops, object.get("ingredient")).result()
            .map(ingredient -> Text.translatable("create.recipe.assembly.deploying_item", new IngredientText(ingredient)))
            .orElseGet(() -> Text.literal("Invalid"));
    }
}