package com.zurrtum.create;

import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemGroup.DisplayContext;
import net.minecraft.item.ItemGroup.Entries;
import net.minecraft.item.ItemStack;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.registry.RegistryKey;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

import static com.zurrtum.create.Create.MOD_ID;

public class AllCreativeModeTabs {
    public static final RegistryKey<ItemGroup> BASE_GROUP = RegistryKey.of(RegistryKeys.ITEM_GROUP, Identifier.of(MOD_ID, "base"));
    public static final RegistryKey<ItemGroup> PALETTES_GROUP = RegistryKey.of(RegistryKeys.ITEM_GROUP, Identifier.of(MOD_ID, "palettes"));

    public static void register() {
        Registry.register(
            Registries.ITEM_GROUP,
            BASE_GROUP,
            ItemGroup.create(null, -1).displayName(Text.translatable("itemGroup.create.base")).icon(() -> new ItemStack(AllBlocks.COGWHEEL))
                .entries(AllCreativeModeTabs::base).build()
        );
        Registry.register(
            Registries.ITEM_GROUP,
            PALETTES_GROUP,
            ItemGroup.create(null, -1).displayName(Text.translatable("itemGroup.create.palettes"))
                .icon(() -> new ItemStack(AllBlocks.ORNATE_IRON_WINDOW)).entries(AllCreativeModeTabs::palettes).build()
        );
    }

    private static void base(DisplayContext displayContext, Entries entries) {
        entries.add(AllItems.COPPER_BACKTANK.getMaxAirStack());
        entries.add(AllItems.NETHERITE_BACKTANK.getMaxAirStack());
        entries.add(AllItems.WRENCH);
        entries.add(AllItems.LINKED_CONTROLLER);
        entries.add(AllItems.POTATO_CANNON);
        entries.add(AllItems.EXTENDO_GRIP);
        entries.add(AllItems.WAND_OF_SYMMETRY);
        entries.add(AllItems.WORLDSHAPER);
        entries.add(AllItems.SCHEMATICANNON);
        entries.add(AllItems.SCHEMATIC_TABLE);
        entries.add(AllItems.SHAFT);
        entries.add(AllItems.COGWHEEL);
        entries.add(AllItems.LARGE_COGWHEEL);
        entries.add(AllItems.GEARBOX);
        entries.add(AllItems.VERTICAL_GEARBOX);
        entries.add(AllItems.CLUTCH);
        entries.add(AllItems.GEARSHIFT);
        entries.add(AllItems.ENCASED_CHAIN_DRIVE);
        entries.add(AllItems.ADJUSTABLE_CHAIN_GEARSHIFT);
        entries.add(AllItems.BELT_CONNECTOR);
        entries.add(AllItems.CHAIN_CONVEYOR);
        entries.add(AllItems.CREATIVE_MOTOR);
        entries.add(AllItems.WATER_WHEEL);
        entries.add(AllItems.LARGE_WATER_WHEEL);
        entries.add(AllItems.ENCASED_FAN);
        entries.add(AllItems.NOZZLE);
        entries.add(AllItems.TURNTABLE);
        entries.add(AllItems.HAND_CRANK);
        entries.add(AllItems.CUCKOO_CLOCK);
        entries.add(AllItems.MILLSTONE);
        entries.add(AllItems.CRUSHING_WHEEL);
        entries.add(AllItems.MECHANICAL_PRESS);
        entries.add(AllItems.MECHANICAL_MIXER);
        entries.add(AllItems.BASIN);
        entries.add(AllItems.EMPTY_BLAZE_BURNER);
        entries.add(AllItems.BLAZE_BURNER);
        entries.add(AllItems.DEPOT);
        entries.add(AllItems.WEIGHTED_EJECTOR);
        entries.add(AllItems.CHUTE);
        entries.add(AllItems.SMART_CHUTE);
        entries.add(AllItems.SPEEDOMETER);
        entries.add(AllItems.STRESSOMETER);
        entries.add(AllItems.WOODEN_BRACKET);
        entries.add(AllItems.METAL_BRACKET);
        entries.add(AllItems.FLUID_PIPE);
        entries.add(AllItems.MECHANICAL_PUMP);
        entries.add(AllItems.SMART_FLUID_PIPE);
        entries.add(AllItems.FLUID_VALVE);
        entries.add(AllItems.COPPER_VALVE_HANDLE);
        entries.add(AllItems.FLUID_TANK);
        entries.add(AllItems.CREATIVE_FLUID_TANK);
        entries.add(AllItems.HOSE_PULLEY);
        entries.add(AllItems.ITEM_DRAIN);
        entries.add(AllItems.SPOUT);
        entries.add(AllItems.PORTABLE_FLUID_INTERFACE);
        entries.add(AllItems.STEAM_ENGINE);
        entries.add(AllItems.STEAM_WHISTLE);
        entries.add(AllItems.MECHANICAL_PISTON);
        entries.add(AllItems.STICKY_MECHANICAL_PISTON);
        entries.add(AllItems.PISTON_EXTENSION_POLE);
        entries.add(AllItems.GANTRY_CARRIAGE);
        entries.add(AllItems.GANTRY_SHAFT);
        entries.add(AllItems.WINDMILL_BEARING);
        entries.add(AllItems.MECHANICAL_BEARING);
        entries.add(AllItems.CLOCKWORK_BEARING);
        entries.add(AllItems.ROPE_PULLEY);
        entries.add(AllItems.ELEVATOR_PULLEY);
        entries.add(AllItems.CART_ASSEMBLER);
        entries.add(AllItems.CONTROLLER_RAIL);
        entries.add(AllItems.LINEAR_CHASSIS);
        entries.add(AllItems.SECONDARY_LINEAR_CHASSIS);
        entries.add(AllItems.RADIAL_CHASSIS);
        entries.add(AllItems.STICKER);
        entries.add(AllItems.CONTRAPTION_CONTROLS);
        entries.add(AllItems.MECHANICAL_DRILL);
        entries.add(AllItems.MECHANICAL_SAW);
        entries.add(AllItems.DEPLOYER);
        entries.add(AllItems.PORTABLE_STORAGE_INTERFACE);
        entries.add(AllItems.REDSTONE_CONTACT);
        entries.add(AllItems.MECHANICAL_HARVESTER);
        entries.add(AllItems.MECHANICAL_PLOUGH);
        entries.add(AllItems.MECHANICAL_ROLLER);
        entries.add(AllItems.SAIL_FRAME);
        entries.add(AllItems.SAIL);
        entries.add(AllItems.ANDESITE_CASING);
        entries.add(AllItems.BRASS_CASING);
        entries.add(AllItems.COPPER_CASING);
        entries.add(AllItems.MECHANICAL_CRAFTER);
        entries.add(AllItems.SEQUENCED_GEARSHIFT);
        entries.add(AllItems.FLYWHEEL);
        entries.add(AllItems.ROTATION_SPEED_CONTROLLER);
        entries.add(AllItems.MECHANICAL_ARM);
        entries.add(AllItems.TRACK);
        entries.add(AllItems.RAILWAY_CASING);
        entries.add(AllItems.SCHEDULE);
        entries.add(AllItems.TRACK_STATION);
        entries.add(AllItems.TRACK_SIGNAL);
        entries.add(AllItems.TRACK_OBSERVER);
        entries.add(AllItems.TRAIN_CONTROLS);
        entries.add(AllItems.ANDESITE_FUNNEL);
        entries.add(AllItems.BRASS_FUNNEL);
        entries.add(AllItems.ANDESITE_TUNNEL);
        entries.add(AllItems.BRASS_TUNNEL);
        entries.add(AllItems.SMART_OBSERVER);
        entries.add(AllItems.THRESHOLD_SWITCH);
        entries.add(AllItems.CREATIVE_CRATE);
        entries.add(AllItems.ITEM_VAULT);
        entries.add(AllItems.ITEM_HATCH);
        entries.add(AllItems.PACKAGER);
        entries.add(AllItems.CARDBOARD_PACKAGE_12X10);
        entries.add(AllItems.CARDBOARD_PACKAGE_10X8);
        entries.add(AllItems.CARDBOARD_PACKAGE_10X12);
        entries.add(AllItems.CARDBOARD_PACKAGE_12X12);
        entries.add(AllItems.REPACKAGER);
        entries.add(AllItems.PACKAGE_FROGPORT);
        entries.add(AllItems.WHITE_POSTBOX);
        entries.add(AllItems.STOCK_LINK);
        entries.add(AllItems.STOCK_TICKER);
        entries.add(AllItems.REDSTONE_REQUESTER);
        entries.add(AllItems.FACTORY_GAUGE);
        entries.add(AllItems.RED_TABLE_CLOTH);
        entries.add(AllItems.ANDESITE_TABLE_CLOTH);
        entries.add(AllItems.BRASS_TABLE_CLOTH);
        entries.add(AllItems.COPPER_TABLE_CLOTH);
        entries.add(AllItems.DISPLAY_LINK);
        entries.add(AllItems.DISPLAY_BOARD);
        entries.add(AllItems.ORANGE_NIXIE_TUBE);
        entries.add(AllItems.ROSE_QUARTZ_LAMP);
        entries.add(AllItems.REDSTONE_LINK);
        entries.add(AllItems.ANALOG_LEVER);
        entries.add(AllItems.PLACARD);
        entries.add(AllItems.PULSE_REPEATER);
        entries.add(AllItems.PULSE_EXTENDER);
        entries.add(AllItems.PULSE_TIMER);
        entries.add(AllItems.POWERED_LATCH);
        entries.add(AllItems.POWERED_TOGGLE_LATCH);
        entries.add(AllItems.PECULIAR_BELL);
        entries.add(AllItems.HAUNTED_BELL);
        entries.add(AllItems.DESK_BELL);
        entries.add(AllItems.BROWN_TOOLBOX);
        entries.add(AllItems.CLIPBOARD);
        entries.add(AllItems.WHEAT_FLOUR);
        entries.add(AllItems.DOUGH);
        entries.add(AllItems.CINDER_FLOUR);
        entries.add(AllItems.ROSE_QUARTZ);
        entries.add(AllItems.POLISHED_ROSE_QUARTZ);
        entries.add(AllItems.POWDERED_OBSIDIAN);
        entries.add(AllItems.STURDY_SHEET);
        entries.add(AllItems.PROPELLER);
        entries.add(AllItems.WHISK);
        entries.add(AllItems.BRASS_HAND);
        entries.add(AllItems.CRAFTER_SLOT_COVER);
        entries.add(AllItems.ELECTRON_TUBE);
        entries.add(AllItems.TRANSMITTER);
        entries.add(AllItems.PULP);
        entries.add(AllItems.CARDBOARD);
        entries.add(AllItems.PRECISION_MECHANISM);
        entries.add(AllItems.BLAZE_CAKE);
        entries.add(AllItems.CREATIVE_BLAZE_CAKE);
        entries.add(AllItems.BAR_OF_CHOCOLATE);
        entries.add(AllItems.SWEET_ROLL);
        entries.add(AllItems.CHOCOLATE_BERRIES);
        entries.add(AllItems.HONEYED_APPLE);
        entries.add(AllItems.BUILDERS_TEA);
        entries.add(AllItems.CARDBOARD_SWORD);
        entries.add(AllItems.RAW_ZINC);
        entries.add(AllItems.ANDESITE_ALLOY);
        entries.add(AllItems.ZINC_INGOT);
        entries.add(AllItems.BRASS_INGOT);
        entries.add(AllItems.COPPER_NUGGET);
        entries.add(AllItems.ZINC_NUGGET);
        entries.add(AllItems.BRASS_NUGGET);
        entries.add(AllItems.EXP_NUGGET);
        entries.add(AllItems.COPPER_SHEET);
        entries.add(AllItems.BRASS_SHEET);
        entries.add(AllItems.IRON_SHEET);
        entries.add(AllItems.GOLDEN_SHEET);
        entries.add(AllItems.CRUSHED_IRON);
        entries.add(AllItems.CRUSHED_GOLD);
        entries.add(AllItems.CRUSHED_COPPER);
        entries.add(AllItems.CRUSHED_ZINC);
        AllItems.CRUSHED_RAW_OSMIUM.addTo(entries);
        AllItems.CRUSHED_RAW_PLATINUM.addTo(entries);
        AllItems.CRUSHED_RAW_SILVER.addTo(entries);
        AllItems.CRUSHED_RAW_TIN.addTo(entries);
        AllItems.CRUSHED_RAW_LEAD.addTo(entries);
        AllItems.CRUSHED_RAW_QUICKSILVER.addTo(entries);
        AllItems.CRUSHED_RAW_ALUMINUM.addTo(entries);
        AllItems.CRUSHED_RAW_URANIUM.addTo(entries);
        AllItems.CRUSHED_RAW_NICKEL.addTo(entries);
        entries.add(AllItems.GOGGLES);
        entries.add(AllItems.SUPER_GLUE);
        entries.add(AllItems.MINECART_COUPLING);
        entries.add(AllItems.CRAFTING_BLUEPRINT);
        entries.add(AllItems.COPPER_DIVING_HELMET);
        entries.add(AllItems.NETHERITE_DIVING_HELMET);
        entries.add(AllItems.COPPER_DIVING_BOOTS);
        entries.add(AllItems.NETHERITE_DIVING_BOOTS);
        entries.add(AllItems.CARDBOARD_HELMET);
        entries.add(AllItems.CARDBOARD_CHESTPLATE);
        entries.add(AllItems.CARDBOARD_LEGGINGS);
        entries.add(AllItems.CARDBOARD_BOOTS);
        entries.add(AllItems.SAND_PAPER);
        entries.add(AllItems.RED_SAND_PAPER);
        entries.add(AllItems.TREE_FERTILIZER);
        entries.add(AllItems.FILTER);
        entries.add(AllItems.ATTRIBUTE_FILTER);
        entries.add(AllItems.PACKAGE_FILTER);
        entries.add(AllItems.EMPTY_SCHEMATIC);
        entries.add(AllItems.SCHEMATIC_AND_QUILL);
        entries.add(AllItems.HONEY_BUCKET);
        entries.add(AllItems.CHOCOLATE_BUCKET);

        entries.add(AllItems.BLAZE_CAKE_BASE, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.WHITE_VALVE_HANDLE, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.ORANGE_VALVE_HANDLE, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.MAGENTA_VALVE_HANDLE, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.LIGHT_BLUE_VALVE_HANDLE, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.YELLOW_VALVE_HANDLE, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.LIME_VALVE_HANDLE, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.PINK_VALVE_HANDLE, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.GRAY_VALVE_HANDLE, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.LIGHT_GRAY_VALVE_HANDLE, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.CYAN_VALVE_HANDLE, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.PURPLE_VALVE_HANDLE, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.BLUE_VALVE_HANDLE, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.BROWN_VALVE_HANDLE, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.GREEN_VALVE_HANDLE, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.RED_VALVE_HANDLE, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.BLACK_VALVE_HANDLE, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.WHITE_TOOLBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.ORANGE_TOOLBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.MAGENTA_TOOLBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.LIGHT_BLUE_TOOLBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.YELLOW_TOOLBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.LIME_TOOLBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.PINK_TOOLBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.GRAY_TOOLBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.LIGHT_GRAY_TOOLBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.CYAN_TOOLBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.PURPLE_TOOLBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.BLUE_TOOLBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.BROWN_TOOLBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.GREEN_TOOLBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.RED_TOOLBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.BLACK_TOOLBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.ORANGE_POSTBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.MAGENTA_POSTBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.LIGHT_BLUE_POSTBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.YELLOW_POSTBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.LIME_POSTBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.PINK_POSTBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.GRAY_POSTBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.LIGHT_GRAY_POSTBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.CYAN_POSTBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.PURPLE_POSTBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.BLUE_POSTBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.BROWN_POSTBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.GREEN_POSTBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.RED_POSTBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.BLACK_POSTBOX, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
    }

    private static void palettes(DisplayContext displayContext, Entries entries) {
        entries.add(AllItems.ANDESITE_LADDER);
        entries.add(AllItems.BRASS_LADDER);
        entries.add(AllItems.COPPER_LADDER);
        entries.add(AllItems.ANDESITE_BARS);
        entries.add(AllItems.BRASS_BARS);
        entries.add(AllItems.COPPER_BARS);
        entries.add(AllItems.ANDESITE_SCAFFOLD);
        entries.add(AllItems.BRASS_SCAFFOLD);
        entries.add(AllItems.COPPER_SCAFFOLD);
        entries.add(AllItems.METAL_GIRDER);
        entries.add(AllItems.COPYCAT_STEP);
        entries.add(AllItems.COPYCAT_PANEL);
        entries.add(AllItems.RED_SEAT);
        entries.add(AllItems.ANDESITE_DOOR);
        entries.add(AllItems.BRASS_DOOR);
        entries.add(AllItems.COPPER_DOOR);
        entries.add(AllItems.TRAIN_DOOR);
        entries.add(AllItems.TRAIN_TRAPDOOR);
        entries.add(AllItems.FRAMED_GLASS_DOOR);
        entries.add(AllItems.FRAMED_GLASS_TRAPDOOR);
        entries.add(AllItems.ZINC_ORE);
        entries.add(AllItems.DEEPSLATE_ZINC_ORE);
        entries.add(AllItems.RAW_ZINC_BLOCK);
        entries.add(AllItems.ZINC_BLOCK);
        entries.add(AllItems.ANDESITE_ALLOY_BLOCK);
        entries.add(AllItems.INDUSTRIAL_IRON_BLOCK);
        entries.add(AllItems.WEATHERED_IRON_BLOCK);
        entries.add(AllItems.BRASS_BLOCK);
        entries.add(AllItems.CARDBOARD_BLOCK);
        entries.add(AllItems.BOUND_CARDBOARD_BLOCK);
        entries.add(AllItems.EXPERIENCE_BLOCK);
        entries.add(AllItems.ROSE_QUARTZ_BLOCK);
        entries.add(AllItems.ROSE_QUARTZ_TILES);
        entries.add(AllItems.SMALL_ROSE_QUARTZ_TILES);
        entries.add(AllItems.COPPER_SHINGLES);
        entries.add(AllItems.EXPOSED_COPPER_SHINGLES);
        entries.add(AllItems.WEATHERED_COPPER_SHINGLES);
        entries.add(AllItems.OXIDIZED_COPPER_SHINGLES);
        entries.add(AllItems.COPPER_SHINGLE_SLAB);
        entries.add(AllItems.EXPOSED_COPPER_SHINGLE_SLAB);
        entries.add(AllItems.WEATHERED_COPPER_SHINGLE_SLAB);
        entries.add(AllItems.OXIDIZED_COPPER_SHINGLE_SLAB);
        entries.add(AllItems.COPPER_SHINGLE_STAIRS);
        entries.add(AllItems.EXPOSED_COPPER_SHINGLE_STAIRS);
        entries.add(AllItems.WEATHERED_COPPER_SHINGLE_STAIRS);
        entries.add(AllItems.OXIDIZED_COPPER_SHINGLE_STAIRS);
        entries.add(AllItems.WAXED_COPPER_SHINGLES);
        entries.add(AllItems.WAXED_EXPOSED_COPPER_SHINGLES);
        entries.add(AllItems.WAXED_WEATHERED_COPPER_SHINGLES);
        entries.add(AllItems.WAXED_OXIDIZED_COPPER_SHINGLES);
        entries.add(AllItems.WAXED_COPPER_SHINGLE_SLAB);
        entries.add(AllItems.WAXED_EXPOSED_COPPER_SHINGLE_SLAB);
        entries.add(AllItems.WAXED_WEATHERED_COPPER_SHINGLE_SLAB);
        entries.add(AllItems.WAXED_OXIDIZED_COPPER_SHINGLE_SLAB);
        entries.add(AllItems.WAXED_COPPER_SHINGLE_STAIRS);
        entries.add(AllItems.WAXED_EXPOSED_COPPER_SHINGLE_STAIRS);
        entries.add(AllItems.WAXED_WEATHERED_COPPER_SHINGLE_STAIRS);
        entries.add(AllItems.WAXED_OXIDIZED_COPPER_SHINGLE_STAIRS);
        entries.add(AllItems.COPPER_TILES);
        entries.add(AllItems.EXPOSED_COPPER_TILES);
        entries.add(AllItems.WEATHERED_COPPER_TILES);
        entries.add(AllItems.OXIDIZED_COPPER_TILES);
        entries.add(AllItems.COPPER_TILE_SLAB);
        entries.add(AllItems.EXPOSED_COPPER_TILE_SLAB);
        entries.add(AllItems.WEATHERED_COPPER_TILE_SLAB);
        entries.add(AllItems.OXIDIZED_COPPER_TILE_SLAB);
        entries.add(AllItems.COPPER_TILE_STAIRS);
        entries.add(AllItems.EXPOSED_COPPER_TILE_STAIRS);
        entries.add(AllItems.WEATHERED_COPPER_TILE_STAIRS);
        entries.add(AllItems.OXIDIZED_COPPER_TILE_STAIRS);
        entries.add(AllItems.WAXED_COPPER_TILES);
        entries.add(AllItems.WAXED_EXPOSED_COPPER_TILES);
        entries.add(AllItems.WAXED_WEATHERED_COPPER_TILES);
        entries.add(AllItems.WAXED_OXIDIZED_COPPER_TILES);
        entries.add(AllItems.WAXED_COPPER_TILE_SLAB);
        entries.add(AllItems.WAXED_EXPOSED_COPPER_TILE_SLAB);
        entries.add(AllItems.WAXED_WEATHERED_COPPER_TILE_SLAB);
        entries.add(AllItems.WAXED_OXIDIZED_COPPER_TILE_SLAB);
        entries.add(AllItems.WAXED_COPPER_TILE_STAIRS);
        entries.add(AllItems.WAXED_EXPOSED_COPPER_TILE_STAIRS);
        entries.add(AllItems.WAXED_WEATHERED_COPPER_TILE_STAIRS);
        entries.add(AllItems.WAXED_OXIDIZED_COPPER_TILE_STAIRS);
        entries.add(AllItems.TILED_GLASS);
        entries.add(AllItems.FRAMED_GLASS);
        entries.add(AllItems.HORIZONTAL_FRAMED_GLASS);
        entries.add(AllItems.VERTICAL_FRAMED_GLASS);
        entries.add(AllItems.TILED_GLASS_PANE);
        entries.add(AllItems.FRAMED_GLASS_PANE);
        entries.add(AllItems.HORIZONTAL_FRAMED_GLASS_PANE);
        entries.add(AllItems.VERTICAL_FRAMED_GLASS_PANE);
        entries.add(AllItems.OAK_WINDOW);
        entries.add(AllItems.SPRUCE_WINDOW);
        entries.add(AllItems.BIRCH_WINDOW);
        entries.add(AllItems.JUNGLE_WINDOW);
        entries.add(AllItems.ACACIA_WINDOW);
        entries.add(AllItems.DARK_OAK_WINDOW);
        entries.add(AllItems.MANGROVE_WINDOW);
        entries.add(AllItems.CRIMSON_WINDOW);
        entries.add(AllItems.WARPED_WINDOW);
        entries.add(AllItems.CHERRY_WINDOW);
        entries.add(AllItems.BAMBOO_WINDOW);
        entries.add(AllItems.ORNATE_IRON_WINDOW);
        entries.add(AllItems.INDUSTRIAL_IRON_WINDOW);
        entries.add(AllItems.WEATHERED_IRON_WINDOW);
        entries.add(AllItems.OAK_WINDOW_PANE);
        entries.add(AllItems.SPRUCE_WINDOW_PANE);
        entries.add(AllItems.BIRCH_WINDOW_PANE);
        entries.add(AllItems.JUNGLE_WINDOW_PANE);
        entries.add(AllItems.ACACIA_WINDOW_PANE);
        entries.add(AllItems.DARK_OAK_WINDOW_PANE);
        entries.add(AllItems.MANGROVE_WINDOW_PANE);
        entries.add(AllItems.CRIMSON_WINDOW_PANE);
        entries.add(AllItems.WARPED_WINDOW_PANE);
        entries.add(AllItems.CHERRY_WINDOW_PANE);
        entries.add(AllItems.BAMBOO_WINDOW_PANE);
        entries.add(AllItems.ORNATE_IRON_WINDOW_PANE);
        entries.add(AllItems.INDUSTRIAL_IRON_WINDOW_PANE);
        entries.add(AllItems.WEATHERED_IRON_WINDOW_PANE);
        entries.add(AllItems.CUT_GRANITE);
        entries.add(AllItems.CUT_GRANITE_STAIRS);
        entries.add(AllItems.CUT_GRANITE_SLAB);
        entries.add(AllItems.CUT_GRANITE_WALL);
        entries.add(AllItems.POLISHED_CUT_GRANITE);
        entries.add(AllItems.POLISHED_CUT_GRANITE_STAIRS);
        entries.add(AllItems.POLISHED_CUT_GRANITE_SLAB);
        entries.add(AllItems.POLISHED_CUT_GRANITE_WALL);
        entries.add(AllItems.CUT_GRANITE_BRICKS);
        entries.add(AllItems.CUT_GRANITE_BRICK_STAIRS);
        entries.add(AllItems.CUT_GRANITE_BRICK_SLAB);
        entries.add(AllItems.CUT_GRANITE_BRICK_WALL);
        entries.add(AllItems.SMALL_GRANITE_BRICKS);
        entries.add(AllItems.SMALL_GRANITE_BRICK_STAIRS);
        entries.add(AllItems.SMALL_GRANITE_BRICK_SLAB);
        entries.add(AllItems.SMALL_GRANITE_BRICK_WALL);
        entries.add(AllItems.LAYERED_GRANITE);
        entries.add(AllItems.GRANITE_PILLAR);
        entries.add(AllItems.CUT_DIORITE);
        entries.add(AllItems.CUT_DIORITE_STAIRS);
        entries.add(AllItems.CUT_DIORITE_SLAB);
        entries.add(AllItems.CUT_DIORITE_WALL);
        entries.add(AllItems.POLISHED_CUT_DIORITE);
        entries.add(AllItems.POLISHED_CUT_DIORITE_STAIRS);
        entries.add(AllItems.POLISHED_CUT_DIORITE_SLAB);
        entries.add(AllItems.POLISHED_CUT_DIORITE_WALL);
        entries.add(AllItems.CUT_DIORITE_BRICKS);
        entries.add(AllItems.CUT_DIORITE_BRICK_STAIRS);
        entries.add(AllItems.CUT_DIORITE_BRICK_SLAB);
        entries.add(AllItems.CUT_DIORITE_BRICK_WALL);
        entries.add(AllItems.SMALL_DIORITE_BRICKS);
        entries.add(AllItems.SMALL_DIORITE_BRICK_STAIRS);
        entries.add(AllItems.SMALL_DIORITE_BRICK_SLAB);
        entries.add(AllItems.SMALL_DIORITE_BRICK_WALL);
        entries.add(AllItems.LAYERED_DIORITE);
        entries.add(AllItems.DIORITE_PILLAR);
        entries.add(AllItems.CUT_ANDESITE);
        entries.add(AllItems.CUT_ANDESITE_STAIRS);
        entries.add(AllItems.CUT_ANDESITE_SLAB);
        entries.add(AllItems.CUT_ANDESITE_WALL);
        entries.add(AllItems.POLISHED_CUT_ANDESITE);
        entries.add(AllItems.POLISHED_CUT_ANDESITE_STAIRS);
        entries.add(AllItems.POLISHED_CUT_ANDESITE_SLAB);
        entries.add(AllItems.POLISHED_CUT_ANDESITE_WALL);
        entries.add(AllItems.CUT_ANDESITE_BRICKS);
        entries.add(AllItems.CUT_ANDESITE_BRICK_STAIRS);
        entries.add(AllItems.CUT_ANDESITE_BRICK_SLAB);
        entries.add(AllItems.CUT_ANDESITE_BRICK_WALL);
        entries.add(AllItems.SMALL_ANDESITE_BRICKS);
        entries.add(AllItems.SMALL_ANDESITE_BRICK_STAIRS);
        entries.add(AllItems.SMALL_ANDESITE_BRICK_SLAB);
        entries.add(AllItems.SMALL_ANDESITE_BRICK_WALL);
        entries.add(AllItems.LAYERED_ANDESITE);
        entries.add(AllItems.ANDESITE_PILLAR);
        entries.add(AllItems.CUT_CALCITE);
        entries.add(AllItems.CUT_CALCITE_STAIRS);
        entries.add(AllItems.CUT_CALCITE_SLAB);
        entries.add(AllItems.CUT_CALCITE_WALL);
        entries.add(AllItems.POLISHED_CUT_CALCITE);
        entries.add(AllItems.POLISHED_CUT_CALCITE_STAIRS);
        entries.add(AllItems.POLISHED_CUT_CALCITE_SLAB);
        entries.add(AllItems.POLISHED_CUT_CALCITE_WALL);
        entries.add(AllItems.CUT_CALCITE_BRICKS);
        entries.add(AllItems.CUT_CALCITE_BRICK_STAIRS);
        entries.add(AllItems.CUT_CALCITE_BRICK_SLAB);
        entries.add(AllItems.CUT_CALCITE_BRICK_WALL);
        entries.add(AllItems.SMALL_CALCITE_BRICKS);
        entries.add(AllItems.SMALL_CALCITE_BRICK_STAIRS);
        entries.add(AllItems.SMALL_CALCITE_BRICK_SLAB);
        entries.add(AllItems.SMALL_CALCITE_BRICK_WALL);
        entries.add(AllItems.LAYERED_CALCITE);
        entries.add(AllItems.CALCITE_PILLAR);
        entries.add(AllItems.CUT_DRIPSTONE);
        entries.add(AllItems.CUT_DRIPSTONE_STAIRS);
        entries.add(AllItems.CUT_DRIPSTONE_SLAB);
        entries.add(AllItems.CUT_DRIPSTONE_WALL);
        entries.add(AllItems.POLISHED_CUT_DRIPSTONE);
        entries.add(AllItems.POLISHED_CUT_DRIPSTONE_STAIRS);
        entries.add(AllItems.POLISHED_CUT_DRIPSTONE_SLAB);
        entries.add(AllItems.POLISHED_CUT_DRIPSTONE_WALL);
        entries.add(AllItems.CUT_DRIPSTONE_BRICKS);
        entries.add(AllItems.CUT_DRIPSTONE_BRICK_STAIRS);
        entries.add(AllItems.CUT_DRIPSTONE_BRICK_SLAB);
        entries.add(AllItems.CUT_DRIPSTONE_BRICK_WALL);
        entries.add(AllItems.SMALL_DRIPSTONE_BRICKS);
        entries.add(AllItems.SMALL_DRIPSTONE_BRICK_STAIRS);
        entries.add(AllItems.SMALL_DRIPSTONE_BRICK_SLAB);
        entries.add(AllItems.SMALL_DRIPSTONE_BRICK_WALL);
        entries.add(AllItems.LAYERED_DRIPSTONE);
        entries.add(AllItems.DRIPSTONE_PILLAR);
        entries.add(AllItems.CUT_DEEPSLATE);
        entries.add(AllItems.CUT_DEEPSLATE_STAIRS);
        entries.add(AllItems.CUT_DEEPSLATE_SLAB);
        entries.add(AllItems.CUT_DEEPSLATE_WALL);
        entries.add(AllItems.POLISHED_CUT_DEEPSLATE);
        entries.add(AllItems.POLISHED_CUT_DEEPSLATE_STAIRS);
        entries.add(AllItems.POLISHED_CUT_DEEPSLATE_SLAB);
        entries.add(AllItems.POLISHED_CUT_DEEPSLATE_WALL);
        entries.add(AllItems.CUT_DEEPSLATE_BRICKS);
        entries.add(AllItems.CUT_DEEPSLATE_BRICK_STAIRS);
        entries.add(AllItems.CUT_DEEPSLATE_BRICK_SLAB);
        entries.add(AllItems.CUT_DEEPSLATE_BRICK_WALL);
        entries.add(AllItems.SMALL_DEEPSLATE_BRICKS);
        entries.add(AllItems.SMALL_DEEPSLATE_BRICK_STAIRS);
        entries.add(AllItems.SMALL_DEEPSLATE_BRICK_SLAB);
        entries.add(AllItems.SMALL_DEEPSLATE_BRICK_WALL);
        entries.add(AllItems.LAYERED_DEEPSLATE);
        entries.add(AllItems.DEEPSLATE_PILLAR);
        entries.add(AllItems.CUT_TUFF);
        entries.add(AllItems.CUT_TUFF_STAIRS);
        entries.add(AllItems.CUT_TUFF_SLAB);
        entries.add(AllItems.CUT_TUFF_WALL);
        entries.add(AllItems.POLISHED_CUT_TUFF);
        entries.add(AllItems.POLISHED_CUT_TUFF_STAIRS);
        entries.add(AllItems.POLISHED_CUT_TUFF_SLAB);
        entries.add(AllItems.POLISHED_CUT_TUFF_WALL);
        entries.add(AllItems.CUT_TUFF_BRICKS);
        entries.add(AllItems.CUT_TUFF_BRICK_STAIRS);
        entries.add(AllItems.CUT_TUFF_BRICK_SLAB);
        entries.add(AllItems.CUT_TUFF_BRICK_WALL);
        entries.add(AllItems.SMALL_TUFF_BRICKS);
        entries.add(AllItems.SMALL_TUFF_BRICK_STAIRS);
        entries.add(AllItems.SMALL_TUFF_BRICK_SLAB);
        entries.add(AllItems.SMALL_TUFF_BRICK_WALL);
        entries.add(AllItems.LAYERED_TUFF);
        entries.add(AllItems.TUFF_PILLAR);
        entries.add(AllItems.ASURINE);
        entries.add(AllItems.CUT_ASURINE);
        entries.add(AllItems.CUT_ASURINE_STAIRS);
        entries.add(AllItems.CUT_ASURINE_SLAB);
        entries.add(AllItems.CUT_ASURINE_WALL);
        entries.add(AllItems.POLISHED_CUT_ASURINE);
        entries.add(AllItems.POLISHED_CUT_ASURINE_STAIRS);
        entries.add(AllItems.POLISHED_CUT_ASURINE_SLAB);
        entries.add(AllItems.POLISHED_CUT_ASURINE_WALL);
        entries.add(AllItems.CUT_ASURINE_BRICKS);
        entries.add(AllItems.CUT_ASURINE_BRICK_STAIRS);
        entries.add(AllItems.CUT_ASURINE_BRICK_SLAB);
        entries.add(AllItems.CUT_ASURINE_BRICK_WALL);
        entries.add(AllItems.SMALL_ASURINE_BRICKS);
        entries.add(AllItems.SMALL_ASURINE_BRICK_STAIRS);
        entries.add(AllItems.SMALL_ASURINE_BRICK_SLAB);
        entries.add(AllItems.SMALL_ASURINE_BRICK_WALL);
        entries.add(AllItems.LAYERED_ASURINE);
        entries.add(AllItems.ASURINE_PILLAR);
        entries.add(AllItems.CRIMSITE);
        entries.add(AllItems.CUT_CRIMSITE);
        entries.add(AllItems.CUT_CRIMSITE_STAIRS);
        entries.add(AllItems.CUT_CRIMSITE_SLAB);
        entries.add(AllItems.CUT_CRIMSITE_WALL);
        entries.add(AllItems.POLISHED_CUT_CRIMSITE);
        entries.add(AllItems.POLISHED_CUT_CRIMSITE_STAIRS);
        entries.add(AllItems.POLISHED_CUT_CRIMSITE_SLAB);
        entries.add(AllItems.POLISHED_CUT_CRIMSITE_WALL);
        entries.add(AllItems.CUT_CRIMSITE_BRICKS);
        entries.add(AllItems.CUT_CRIMSITE_BRICK_STAIRS);
        entries.add(AllItems.CUT_CRIMSITE_BRICK_SLAB);
        entries.add(AllItems.CUT_CRIMSITE_BRICK_WALL);
        entries.add(AllItems.SMALL_CRIMSITE_BRICKS);
        entries.add(AllItems.SMALL_CRIMSITE_BRICK_STAIRS);
        entries.add(AllItems.SMALL_CRIMSITE_BRICK_SLAB);
        entries.add(AllItems.SMALL_CRIMSITE_BRICK_WALL);
        entries.add(AllItems.LAYERED_CRIMSITE);
        entries.add(AllItems.CRIMSITE_PILLAR);
        entries.add(AllItems.LIMESTONE);
        entries.add(AllItems.CUT_LIMESTONE);
        entries.add(AllItems.CUT_LIMESTONE_STAIRS);
        entries.add(AllItems.CUT_LIMESTONE_SLAB);
        entries.add(AllItems.CUT_LIMESTONE_WALL);
        entries.add(AllItems.POLISHED_CUT_LIMESTONE);
        entries.add(AllItems.POLISHED_CUT_LIMESTONE_STAIRS);
        entries.add(AllItems.POLISHED_CUT_LIMESTONE_SLAB);
        entries.add(AllItems.POLISHED_CUT_LIMESTONE_WALL);
        entries.add(AllItems.CUT_LIMESTONE_BRICKS);
        entries.add(AllItems.CUT_LIMESTONE_BRICK_STAIRS);
        entries.add(AllItems.CUT_LIMESTONE_BRICK_SLAB);
        entries.add(AllItems.CUT_LIMESTONE_BRICK_WALL);
        entries.add(AllItems.SMALL_LIMESTONE_BRICKS);
        entries.add(AllItems.SMALL_LIMESTONE_BRICK_STAIRS);
        entries.add(AllItems.SMALL_LIMESTONE_BRICK_SLAB);
        entries.add(AllItems.SMALL_LIMESTONE_BRICK_WALL);
        entries.add(AllItems.LAYERED_LIMESTONE);
        entries.add(AllItems.LIMESTONE_PILLAR);
        entries.add(AllItems.OCHRUM);
        entries.add(AllItems.CUT_OCHRUM);
        entries.add(AllItems.CUT_OCHRUM_STAIRS);
        entries.add(AllItems.CUT_OCHRUM_SLAB);
        entries.add(AllItems.CUT_OCHRUM_WALL);
        entries.add(AllItems.POLISHED_CUT_OCHRUM);
        entries.add(AllItems.POLISHED_CUT_OCHRUM_STAIRS);
        entries.add(AllItems.POLISHED_CUT_OCHRUM_SLAB);
        entries.add(AllItems.POLISHED_CUT_OCHRUM_WALL);
        entries.add(AllItems.CUT_OCHRUM_BRICKS);
        entries.add(AllItems.CUT_OCHRUM_BRICK_STAIRS);
        entries.add(AllItems.CUT_OCHRUM_BRICK_SLAB);
        entries.add(AllItems.CUT_OCHRUM_BRICK_WALL);
        entries.add(AllItems.SMALL_OCHRUM_BRICKS);
        entries.add(AllItems.SMALL_OCHRUM_BRICK_STAIRS);
        entries.add(AllItems.SMALL_OCHRUM_BRICK_SLAB);
        entries.add(AllItems.SMALL_OCHRUM_BRICK_WALL);
        entries.add(AllItems.LAYERED_OCHRUM);
        entries.add(AllItems.OCHRUM_PILLAR);
        entries.add(AllItems.SCORIA);
        entries.add(AllItems.CUT_SCORIA);
        entries.add(AllItems.CUT_SCORIA_STAIRS);
        entries.add(AllItems.CUT_SCORIA_SLAB);
        entries.add(AllItems.CUT_SCORIA_WALL);
        entries.add(AllItems.POLISHED_CUT_SCORIA);
        entries.add(AllItems.POLISHED_CUT_SCORIA_STAIRS);
        entries.add(AllItems.POLISHED_CUT_SCORIA_SLAB);
        entries.add(AllItems.POLISHED_CUT_SCORIA_WALL);
        entries.add(AllItems.CUT_SCORIA_BRICKS);
        entries.add(AllItems.CUT_SCORIA_BRICK_STAIRS);
        entries.add(AllItems.CUT_SCORIA_BRICK_SLAB);
        entries.add(AllItems.CUT_SCORIA_BRICK_WALL);
        entries.add(AllItems.SMALL_SCORIA_BRICKS);
        entries.add(AllItems.SMALL_SCORIA_BRICK_STAIRS);
        entries.add(AllItems.SMALL_SCORIA_BRICK_SLAB);
        entries.add(AllItems.SMALL_SCORIA_BRICK_WALL);
        entries.add(AllItems.LAYERED_SCORIA);
        entries.add(AllItems.SCORIA_PILLAR);
        entries.add(AllItems.SCORCHIA);
        entries.add(AllItems.CUT_SCORCHIA);
        entries.add(AllItems.CUT_SCORCHIA_STAIRS);
        entries.add(AllItems.CUT_SCORCHIA_SLAB);
        entries.add(AllItems.CUT_SCORCHIA_WALL);
        entries.add(AllItems.POLISHED_CUT_SCORCHIA);
        entries.add(AllItems.POLISHED_CUT_SCORCHIA_STAIRS);
        entries.add(AllItems.POLISHED_CUT_SCORCHIA_SLAB);
        entries.add(AllItems.POLISHED_CUT_SCORCHIA_WALL);
        entries.add(AllItems.CUT_SCORCHIA_BRICKS);
        entries.add(AllItems.CUT_SCORCHIA_BRICK_STAIRS);
        entries.add(AllItems.CUT_SCORCHIA_BRICK_SLAB);
        entries.add(AllItems.CUT_SCORCHIA_BRICK_WALL);
        entries.add(AllItems.SMALL_SCORCHIA_BRICKS);
        entries.add(AllItems.SMALL_SCORCHIA_BRICK_STAIRS);
        entries.add(AllItems.SMALL_SCORCHIA_BRICK_SLAB);
        entries.add(AllItems.SMALL_SCORCHIA_BRICK_WALL);
        entries.add(AllItems.LAYERED_SCORCHIA);
        entries.add(AllItems.SCORCHIA_PILLAR);
        entries.add(AllItems.VERIDIUM);
        entries.add(AllItems.CUT_VERIDIUM);
        entries.add(AllItems.CUT_VERIDIUM_STAIRS);
        entries.add(AllItems.CUT_VERIDIUM_SLAB);
        entries.add(AllItems.CUT_VERIDIUM_WALL);
        entries.add(AllItems.POLISHED_CUT_VERIDIUM);
        entries.add(AllItems.POLISHED_CUT_VERIDIUM_STAIRS);
        entries.add(AllItems.POLISHED_CUT_VERIDIUM_SLAB);
        entries.add(AllItems.POLISHED_CUT_VERIDIUM_WALL);
        entries.add(AllItems.CUT_VERIDIUM_BRICKS);
        entries.add(AllItems.CUT_VERIDIUM_BRICK_STAIRS);
        entries.add(AllItems.CUT_VERIDIUM_BRICK_SLAB);
        entries.add(AllItems.CUT_VERIDIUM_BRICK_WALL);
        entries.add(AllItems.SMALL_VERIDIUM_BRICKS);
        entries.add(AllItems.SMALL_VERIDIUM_BRICK_STAIRS);
        entries.add(AllItems.SMALL_VERIDIUM_BRICK_SLAB);
        entries.add(AllItems.SMALL_VERIDIUM_BRICK_WALL);
        entries.add(AllItems.LAYERED_VERIDIUM);
        entries.add(AllItems.VERIDIUM_PILLAR);

        entries.add(AllItems.WHITE_SEAT, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.ORANGE_SEAT, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.MAGENTA_SEAT, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.LIGHT_BLUE_SEAT, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.YELLOW_SEAT, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.LIME_SEAT, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.PINK_SEAT, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.GRAY_SEAT, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.LIGHT_GRAY_SEAT, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.CYAN_SEAT, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.PURPLE_SEAT, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.BLUE_SEAT, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.BROWN_SEAT, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.GREEN_SEAT, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.BLACK_SEAT, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.WHITE_TABLE_CLOTH, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.ORANGE_TABLE_CLOTH, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.MAGENTA_TABLE_CLOTH, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.LIGHT_BLUE_TABLE_CLOTH, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.YELLOW_TABLE_CLOTH, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.LIME_TABLE_CLOTH, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.PINK_TABLE_CLOTH, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.GRAY_TABLE_CLOTH, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.LIGHT_GRAY_TABLE_CLOTH, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.CYAN_TABLE_CLOTH, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.PURPLE_TABLE_CLOTH, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.BLUE_TABLE_CLOTH, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.BROWN_TABLE_CLOTH, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.GREEN_TABLE_CLOTH, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
        entries.add(AllItems.BLACK_TABLE_CLOTH, ItemGroup.StackVisibility.SEARCH_TAB_ONLY);
    }
}
